version: '3'

services:
    dev:
        container_name: devsys
        image: devsys
        restart: "no"
        build:
            context: .
            dockerfile: Dockerfile
        command: /bin/bash
        volumes:
            - code:/code
volumes:
    code:
        driver: local
        driver_opts:
            type: none
            device: '/host_mnt/d/code/lab/webasm-concept'
            o: bind